#!/usr/bin/env bash
set -e
CURRENT_DIR=$(echo $PWD)
OS=$(uname -s)
SUBOS=$(cat /etc/*-release | grep DISTRIB_ID | sed s/DISTRIB_ID=//)
HOST=$(hostname)

# Format all nix files
echo "Formatting nix files..."
for file in $(find . -name "*.nix"); do
	alejandra $file &>/dev/null
done

# Show changes
git diff --stat
if [ "$OS" = "Darwin" ]; then
	echo "Nix Darwin Rebuilding..."
	darwin-rebuild switch --flake .#jacob-germany &>~/.logs/latest-rebuild.log || (cat ~/.logs/latest-rebuild.log | grep --color error && false)
	gen="Nix Darwin: $(darwin-rebuild --list-generations | sed -n '$p' | awk '{print $1}')"
elif [ "$SUBOS" = nixos ]; then
	echo "NixOS Rebuilding..."
	nh os switch .
	gen="NixOS: $(nix-env --list-generations | sed -n '$p' | awk '{print $1}')"
else
	echo "Home-Manager Rebuilding..."
	home-manager build switch &>~/.logs/home-manager-rebuild.log || (cat ~/.logs/latest-rebuild.log | grep --color error && false)
	gen="Home Manager: $(home-manager generations | sed -n '1p' | awk '{print $5}')"
fi
git commit -am "Rebuild: $gen"
cd $CURRENT_DIR
