#!/usr/bin/env bash
CURRENT_DIR=$(echo $PWD)
cd ~/.config/home-manager/
nvim .
for file in $(find . -name "*.nix"); do
	alejandra $file &>/dev/null
done
git diff -U0 *.nix
echo "Home-Manager Rebuilding..."
home-manager build switch &>~/.logs/home-manager-rebuild.log || (cat ~/.logs/home-manager-rebuild.log | grep --color=error && false)
gen=$(home-manager generations | sed -n '1p' | awk '{print $5}')
git commit -am "Home-Manager Rebuild: $gen"
cd $CURRENT_DIR
