# CodeGemma 7B-code
#[model.completion.http]
#kind = "ollama/completion"
#model_name = "codegemma:7b-code"
#api_endpoint = "http://localhost:11434"
#prompt_template = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>"  # Example prompt template for CodeLlama model series.

# CodeGemma 2B-Code
[model.completion.http]
kind = "ollama/completion"
model_name = "codegemma:2b-code"
api_endpoint = "http://localhost:11434"
prompt_template = "<|fim_prefix|>{prefix}<|fim_suffix|>{suffix}<|fim_middle|>"  # Example prompt template for CodeLlama model series.
