# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1c2c8a54-7904-4a1b-8957-9d2c2f3925b7";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/980B-B509";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/media" = {
    device = "192.168.88.11:/volume1/media";
    fsType = "nfs";
    options = [
      "x-systemd.automount"
      "x-systemd.mount-timeout=10"
      "_netdev" # Wait for network
      "nofail" # Don't fail boot if mount fails
      "soft" # Return error instead of hanging
      "timeo=30" # 3 second timeout per retry
      "retrans=3" # 3 retries
    ];
  };
  fileSystems."/adult" = {
    device = "192.168.88.11:/volume1/adult";
    fsType = "nfs";
    options = [
      "x-systemd.automount"
      "x-systemd.mount-timeout=10"
      "_netdev"
      "nofail"
      "soft"
      "timeo=30"
      "retrans=3"
    ];
  };
  fileSystems."/cache" = {
    device = "/dev/disk/by-uuid/b1540301-3523-4ee6-a53f-d6c7e9af2f39";
    fsType = "ext4";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u2u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
