name: "Build Steam Deck Packages"
on:
  pull_request:
  push:
jobs:
  start-runner:
    timeout-minutes: 5              # normally it only takes 1-2 minutes
    name: Start self-hosted EC2 runner   
    runs-on: ubuntu-latest
    permissions:
      actions: write        
    steps:      
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: NextChapterSoftware/ec2-action-builder@v1.10
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws_region: "ap-southeast-2"
          ec2_instance_type: c6i.4xlarge
          ec2_root_disk_size_gb: "100"
          ec2_ami_id: ami-09e143e99e8fa74f9
          ec2_subnet_id: "subnet-e54cb9ad"
          ec2_security_group_id: "sg-c4dfe0b2"
          ec2_instance_ttl: 40                # Optional (default is 60 minutes)
          ec2_spot_instance_strategy: BestEffort

  run-build:
    timeout-minutes: 60
    needs:
      - start-runner
    runs-on: ${{ github.run_id }}
    steps:
    - run: mkdir -p /home/runner && chmod -R 777 /home/runner
    - run: echo "HOME=/home/runner" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: jpyke3
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.jacob-japan.config.system.build.toplevel
    - run: nix flake check
